live_config_reload = true

[env]
TERM = "alacritty"

[window]
padding = { x = 0, y = 0 }
decorations = "Buttonless"
opacity = 0.82
blur = true
startup_mode = "SimpleFullscreen"
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14

[selection]
save_to_clipboard = true
